export const MAX_SOURCE_BLOCKS = 30;
export const MAX_SOURCE_BLOCK_TEXT_LENGTH = 12000;
export const MAX_DIAGNOSIS_QUESTIONS = 12;
export const MAX_CONFIRMED_SOURCE_BLOCKS = MAX_SOURCE_BLOCKS + MAX_DIAGNOSIS_QUESTIONS;
